name: '🚀 Feature Request'
description: 'Suggest a new utility or enhancement'

body:
  - type: dropdown
    id: affected-packages
    attributes:
      label: Which @signality/* package(s) are relevant/related to the feature request?
      options:
        - core
        - cdk-interop
      multiple: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: alternatives-considered
    attributes:
      label: Alternatives considered
    validations:
      required: true
