name: ✅ Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/workflows/composite

      - name: Build packages
        run: pnpm build

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/workflows/composite

      - name: Run tests
        run: pnpm test

  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/workflows/composite

      - name: Run ESLint
        run: pnpm lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Install
        uses: ./.github/workflows/composite

      - name: Run prettier
        run: pnpm prettier
